// Copyright 2020 Khronos Group.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_external_memory_acquire_unmodified.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2022-07-04
*Contributors*::
  - Chad Versace, Google
  - Chia-I Wu, Google
  - James Jones, NVIDIA
  - Yiwei Zhang, Google

=== Description

This extension provides a performance hint
that may: reduce the runtime cost of memory barriers
that acquire ownership of a resource from an external queue family
(such as ename:VK_QUEUE_FAMILY_FOREIGN_EXT).
When the application releases ownership of a resource to an external queue
family and later re-acquires ownership,
the application should: provide the hint to the acquire operation
if the resource's external memory remained unmodified between the release and
acquire.

include::{generated}/interfaces/VK_EXT_external_memory_acquire_unmodified.adoc[]

=== Version History

* Revision 1, 2022-07-04 (Chad Versace)
  - Initial revision
